name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Person.java
      id: person-java
      uses: education/autograding-io-grader@v1
      with:
        test-name: Person.java
        command: javac Person.java && java Person
        input: ''
        expected-output: "Person 1:Jhon Doe\r\nPerson 2:Alice Smith\r\nAverage Age:27.5"
        comparison-method: exact
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        PERSON-JAVA_RESULTS: "${{steps.person-java.outputs.result}}"
      with:
        runners: person-java
